export enum FilterType {
  ALLROOMS = 'allRooms',
  ROOMNUMBER = 'roomNumber',
  ALLINQUIRIES = 'allInquiries',
  INQUIRYBYOBJECTID = 'inquiryByObjectId',
  ADVANCESEARCHINQUIRY = 'advanceSearchInquiry',
  TRANSIENTPRIVATEROOMS = 'transientPrivateRooms',
  TRANSIENTPRIVATEROOMBYOBJECTID = 'transientPrivateRoomByObjectId',
  ADVANCESEARCHTRANSIENTPRIVATEROOMS = 'advanceSearchTransientPrivateRooms',
  BEDSPACEROOMS = 'bedspaceRooms',
  BEDSPACEROOMBYOBJECTID = 'bedspaceRoomByObjectId',
  ADVANCESEARCHBEDSPACEROOMS = 'advanceSearchBedspaceRooms',
  ROOMSBYTENANTOBJECTID = 'roomsByTenantObjectId',
  ALLTENANTS = 'allTenants',
  TENANTBYKEYSTROKE = 'tenantByKeyStroke',
  TENANTBYOBJECTID = 'tenantByObjectId',
  ADVANCESEARCHTENANT = 'advanceSearchTenant',
  ALLENTRIES = 'allEntries',
  ENTRYBYOBJECTID = 'entryByObjectId',
  ADVANCESEARCHENTRY = 'advanceSearchEntry',
  ALLROOMPAYMENTS = 'allRoomPayments',
  ROOMPAYMENTBYOBJECTID = 'roomPaymentByObjectId',
  ADVANCESEARCHROOMPAYMENT = 'advanceSearchRoomPayment',
  ROOMPAYMENTSINFOURMONTHS = 'roomPaymentsInFourMonths',
  ALLUNSETTLEBILLS = 'allUnsettleBills',
  UNSETTLEBILLBYOBJECTID = 'unsettleBillByObjectId',
}
